const SectionProjects = () => {

    return (
        <>
            <h1 style={{ marginTop: "100px" }}>ABOUT ME</h1>
            <div className="contenedorSecciones">
                <h1>Titulo</h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga laborum obcaecati aut in officiis, vel nulla sed quis quo sit corporis numquam itaque temporibus aliquam ullam quam quos corrupti eligendi.</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corrupti ipsum aliquid vero, at reprehenderit aut, totam est vel nobis corporis nisi cum pariatur! Exercitationem modi, id nemo fuga laborum facere eos aliquam accusamus eligendi voluptas eaque quisquam in. Deleniti illum non molestiae odit at soluta, voluptatem quia blanditiis debitis magni temporibus, sit cumque harum officiis modi eaque est nostrum aut laudantium quibusdam consequuntur, enim voluptate. Libero accusantium ipsa ducimus, obcaecati inventore ex quaerat nihil. Eius, facilis molestiae? Debitis quas culpa dolorem beatae modi cum officia voluptatibus ipsam atque eos, in totam, commodi quisquam esse perspiciatis magnam exercitationem alias est amet illo quis perferendis fuga. Rem quo velit possimus a impedit quos soluta fugit? Aut tempore sequi rerum minima velit nulla quam fugit fugiat eligendi ipsa distinctio quidem, porro ex enim dolores animi ullam eveniet vel. Ad suscipit iusto officia culpa cumque minima in voluptas dolore, error odit ducimus repellendus deserunt labore neque fugiat accusamus a placeat id ipsa nemo sunt. Placeat voluptate tempora laboriosam dolor maiores ipsa autem quis blanditiis, sequi quia, vero molestias sit possimus et omnis libero neque quod assumenda explicabo commodi ipsum! Fuga perspiciatis harum doloremque, nobis eius repellendus saepe et pariatur sed dolorem animi natus amet.</p>
                <h1>Titulo</h1>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fuga laborum obcaecati aut in officiis, vel nulla sed quis quo sit corporis numquam itaque temporibus aliquam ullam quam quos corrupti eligendi.</p>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corrupti ipsum aliquid vero, at reprehenderit aut, totam est vel nobis corporis nisi cum pariatur! Exercitationem modi, id nemo fuga laborum facere eos aliquam accusamus eligendi voluptas eaque quisquam in. Deleniti illum non molestiae odit at soluta, voluptatem quia blanditiis debitis magni temporibus, sit cumque harum officiis modi eaque est nostrum aut laudantium quibusdam consequuntur, enim voluptate. Libero accusantium ipsa ducimus, obcaecati inventore ex quaerat nihil. Eius, facilis molestiae? Debitis quas culpa dolorem beatae modi cum officia voluptatibus ipsam atque eos, in totam, commodi quisquam esse perspiciatis magnam exercitationem alias est amet illo quis perferendis fuga. Rem quo velit possimus a impedit quos soluta fugit? Aut tempore sequi rerum minima velit nulla quam fugit fugiat eligendi ipsa distinctio quidem, porro ex enim dolores animi ullam eveniet vel. Ad suscipit iusto officia culpa cumque minima in voluptas dolore, error odit ducimus repellendus deserunt labore neque fugiat accusamus a placeat id ipsa nemo sunt. Placeat voluptate tempora laboriosam dolor maiores ipsa autem quis blanditiis, sequi quia, vero molestias sit possimus et omnis libero neque quod assumenda explicabo commodi ipsum! Fuga perspiciatis harum doloremque, nobis eius repellendus saepe et pariatur sed dolorem animi natus amet.</p>

            </div>
        </>

    )
}
export default SectionProjects;