import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ThreeScene from '../components/ThreeScene'
import ThreeScene2 from '../components/ThreeScene2';
import SectionProjects from '../components/SectionProjects';
import SectionSkills from '../components/SectionSkills';
import SectionContact from '../components/SectionContact';
import SectionAboutMe from '../components/SectionAbout';
import SectionBlog from '../components/SectionBlog';


import { useEffect, useState } from 'react';
export default function Home() {


  const [opciones, setopciones] = useState(0);
  const [isLoading, setIsLoading] = useState(false)

  function handleClickOpciones(newOption) {
    if (newOption != opciones) {
      setIsLoading(!isLoading);
      setTimeout(() => {
        setopciones(newOption);
      }, 2000);
    }
  }

  useEffect(() => {
    setIsLoading(!isLoading);
  }, [opciones])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`overlay ${!isLoading ? 'overlay-hidden' : ''}`}>
        <nav style={{ position: "fixed", zIndex: "1" }}>
          <h1 >
            Welcome to my portfolio
          </h1>
        </nav>

        <div style={{ position: "fixed" }} >
          {opciones === 0 ? (
            <div>
              <ThreeScene />
            </div>
          ) : opciones === 1 ? (
            <div>
              <ThreeScene2 componente={SectionProjects} />
            </div>
          ) : opciones === 2 ? (
            <div>
              <ThreeScene2 componente={SectionSkills} />
            </div>
          ) : opciones === 3 ? (
            <div>
              <ThreeScene2 componente={SectionAboutMe} />
            </div>
          ) : opciones === 4 ? (
            <div>
              <ThreeScene2 componente={SectionBlog} />
            </div>
          ) : opciones === 5 ? (
            <div>
              <ThreeScene2 componente={SectionContact} />
            </div>
          ) : (
            <p>No option selected</p>
          )}
          <ThreeScene />
        </div>
        <div className={` ${opciones !== 0 ? 'boxOptionesUp' : 'boxOptions'}`}>
          <a className={opciones === 0 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(0) }}>Inicio</a>
          <a className={opciones === 1 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(1) }}>Proyectos</a>
          <a className={opciones === 2 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(2) }}>Skills</a>
          <a className={opciones === 3 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(3) }}>About Me</a>
          <a className={opciones === 4 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(4) }}>Blog</a>
          <a className={opciones === 5 ? 'selectedOption' : ''} onClick={() => { handleClickOpciones(5) }}>Contacto</a>

        </div>

      </div>



      <main className={styles.main}>



      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
